[package]
name = "music-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
aws-config = "1.11.0"
aws-sdk-s3 = "1.143.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.4"
uuid = { version = "1.25.0", features = ["v4"] }
