FROM rust:1.97-alpine3.23 AS builder
WORKDIR /app

RUN apk add protoc

COPY . .
RUN cargo build

FROM alpine:3.23

RUN apk add ca-certificates

COPY --from=builder /app/target/debug/music-storage .
COPY config config
CMD ["./music-storage"]